require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/migrate/*'
    - 'bin/*'
    - 'spec/dummy/db/schema.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Lint/Loop:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
