default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cross_promotion_app_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: cross_promotion_app_test
  username: postgres
  password: postgres
